import { Link } from 'react-router-dom';
import { Download } from 'lucide-react';

export default function Demo() {
    return (
        <div className="page-container glass-card">
            <div className="page-header demo-header">
                <h1 className="hero-headline">See the Engine in action.</h1>
                <p className="hero-subtext">Don't take our word for it. Review authentic validation reports generated by our AI.</p>
            </div>

            <div className="demo-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '2rem', marginTop: '3rem' }}>
                
                {/* Case 1 */}
                <div className="demo-card modern-card">
                    <div className="demo-badge A-grade" style={{ background: 'rgba(16,185,129,0.2)', color: '#10b981', padding: '0.25rem 0.75rem', borderRadius: '12px', display: 'inline-block', fontWeight: 'bold', fontSize: '0.85rem' }}>Investment Grade: A</div>
                    <h3 style={{ marginTop: '1rem', fontSize: '1.5rem' }}>B2B SaaS Auto-Scheduler</h3>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', margin: '1rem 0', minHeight: '60px' }}>
                        "An AI calendar agent that negotiates meeting times via email directly with clients."
                    </p>
                    <div className="verdict-bar" style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', marginBottom: '1.5rem' }}>
                        <span>Verdict</span>
                        <span style={{ color: '#10b981', fontWeight: 'bold' }}>✅ VALIDATE</span>
                    </div>
                    <button className="btn-secondary" style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }} onClick={() => alert('Demo PDF download coming soon!')}>
                        <Download size={18} /> View Sample Report
                    </button>
                </div>

                {/* Case 2 */}
                <div className="demo-card modern-card">
                    <div className="demo-badge C-grade" style={{ background: 'rgba(245,158,11,0.2)', color: '#f59e0b', padding: '0.25rem 0.75rem', borderRadius: '12px', display: 'inline-block', fontWeight: 'bold', fontSize: '0.85rem' }}>Investment Grade: C</div>
                    <h3 style={{ marginTop: '1rem', fontSize: '1.5rem' }}>D2C Smart Coffee Mug</h3>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', margin: '1rem 0', minHeight: '60px' }}>
                        "A bluetooth-enabled mug that keeps coffee at the perfect temperature."
                    </p>
                    <div className="verdict-bar" style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', marginBottom: '1.5rem' }}>
                        <span>Verdict</span>
                        <span style={{ color: '#f59e0b', fontWeight: 'bold' }}>🔄 REWORK (Crowded)</span>
                    </div>
                    <button className="btn-secondary" style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }} onClick={() => alert('Demo PDF download coming soon!')}>
                        <Download size={18} /> View Sample Report
                    </button>
                </div>

                {/* Case 3 */}
                <div className="demo-card modern-card">
                    <div className="demo-badge B-grade" style={{ background: 'rgba(59,130,246,0.2)', color: '#3b82f6', padding: '0.25rem 0.75rem', borderRadius: '12px', display: 'inline-block', fontWeight: 'bold', fontSize: '0.85rem' }}>Investment Grade: B</div>
                    <h3 style={{ marginTop: '1rem', fontSize: '1.5rem' }}>Web3 GPU Network</h3>
                    <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', margin: '1rem 0', minHeight: '60px' }}>
                        "A distributed network allowing gamers to rent out idle GPU compute for AI training."
                    </p>
                    <div className="verdict-bar" style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', marginBottom: '1.5rem' }}>
                        <span>Verdict</span>
                        <span style={{ color: '#10b981', fontWeight: 'bold' }}>✅ VALIDATE</span>
                    </div>
                    <button className="btn-secondary" style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }} onClick={() => alert('Demo PDF download coming soon!')}>
                        <Download size={18} /> View Sample Report
                    </button>
                </div>

            </div>

            <div className="privacy-banner" style={{ textAlign: 'center', marginTop: '4rem', padding: '2rem', background: 'transparent', border: '1px dashed rgba(255,255,255,0.2)', borderRadius: '12px' }}>
                <p style={{ color: 'var(--text-muted)' }}>🔒 <strong>Ironclad Confidentiality:</strong> These are public examples. Your ideas are strictly confidential. We never use user submissions to train our AI models.</p>
            </div>

            <div style={{ textAlign: 'center', marginTop: '3rem', paddingBottom: '2rem' }}>
                <Link to="/" className="btn-validate" style={{ textDecoration: 'none', display: 'inline-block' }}>Run Your Own Report →</Link>
            </div>
        </div>
    );
}
